project:
  type: website
  output-dir: docs

website:
  title: "Bea Taylor"
  navbar:
    toggle-position: right
    background: primary
    search: false
    logo: images/logo_long.png
    logo-alt: "Bea Taylor logo"
    title: false
    collapse-below: lg
    right:
    - posts/index.qmd
    - paper_explainers/index.qmd
    - about.qmd
  page-footer: 
    left: "Copyright 2025, Bea Taylor" 
format:
  html:
    theme: custom.scss
    toc: true
    highlight-style: github



