project:
  type: website
  output-dir: docs

website:
  title: "Bea Taylor"
  site-url: https://bea-taylor.github.io/
  repo-url: https://github.com/Bea-Taylor/bea-taylor.github.io
  navbar:
    background: primary
    search: false
    logo: images/logo_long.png
    logo-alt: "Bea Taylor logo"
    title: false
    pinned: false
    # collapse-below: lg
    right:
    - posts/index.qmd
    - paper_explainers/index.qmd
    - about.qmd
  page-footer: 
    left: "Copyright 2025, Bea Taylor" 
    right: 
      - icon: github
        href: https://github.com/Bea-Taylor/bea-taylor.github.io
    background: primary

format:
  html:
    theme: btaylor.scss
    css: btaylor.css
    toc: true
    highlight-style: github
    html-math-method: katex
    allow-html: true



