project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: primary
    search: false
    logo: images/bea_name_logo_2.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/Bea-Taylor
  page-footer: 
    left: "" 
    background: light

format:
  html:
    theme: custom.scss
    toc: true
    highlight-style: github



